import { useState } from "react";
import { getAllMembers } from "../services/members/memberService/membersService";
import { getLookupList, seedLookupListIfEmpty } from "../services/settings/lookupListsService";
import { getRotationQueue, seedRotationQueueIfEmpty, saveRotationQueue } from "../services/rotationQueue/rotationQueueService";
import { getLineUpsInRange, saveLineUp } from "../services/programLineUp/programLineUpService";
import { generateLineUpBatch, type QueueSnapshot } from "../services/programLineUp/lineUpGeneratorServices";
import { isCouncilPoolMember, isWorkerPoolMember, isWedPresiderPoolMember } from "../types/member";
import type { RotationRole } from "../types/rotationQueue";

const DEFAULT_CATEGORIES = ["Men", "Women", "Youth Boys", "Youth Girls", "Young Adult/Young Professional"];
const ALL_ROLES: RotationRole[] = [
  "presiderCouncil",
  "speakerWorker",
  "wedPresiderPool",
  "usherCategory",
  "specialNumberCategory",
  "flowerFamily",
];

export interface AutoGenerateResult {
  generatedCount: number;
  skippedDates: string[];
}

export default function useAutoGenerateLineUps(currentUser: string) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate(dateFrom: string, dateTo: string): Promise<AutoGenerateResult | null> {
    setGenerating(true);
    setError(null);
    try {
      const [members, categoryOptions, existing] = await Promise.all([
        getAllMembers().then((all) => all.filter((m) => !m.isArchived)),
        seedLookupListIfEmpty("category", DEFAULT_CATEGORIES).then(() => getLookupList("category")),
        getLineUpsInRange(dateFrom, dateTo),
      ]);

      const councilIds = members.filter(isCouncilPoolMember).map((m) => m.id);
      const workerIds = members.filter(isWorkerPoolMember).map((m) => m.id);
      const wedPresiderIds = members.filter(isWedPresiderPoolMember).map((m) => m.id);

      // Seed every role's queue if it doesn't exist yet (no-op if it does).
      await Promise.all([
        seedRotationQueueIfEmpty("presiderCouncil", councilIds),
        seedRotationQueueIfEmpty("speakerWorker", workerIds),
        seedRotationQueueIfEmpty("wedPresiderPool", wedPresiderIds),
        seedRotationQueueIfEmpty("usherCategory", categoryOptions),
        seedRotationQueueIfEmpty("specialNumberCategory", categoryOptions),
        seedRotationQueueIfEmpty("flowerFamily", []),
      ]);

      const queueDocs = await Promise.all(ALL_ROLES.map((role) => getRotationQueue(role)));
      const startingQueues = {} as QueueSnapshot;
      ALL_ROLES.forEach((role, i) => {
        startingQueues[role] = queueDocs[i]?.items ?? [];
      });

      const existingDates = new Set(existing.map((e) => e.date));

      const { entries, finalQueues, skippedDates } = generateLineUpBatch(
        dateFrom,
        dateTo,
        members,
        categoryOptions,
        startingQueues,
        existingDates,
        currentUser
      );

      // Persist every newly generated entry, then persist the final queue
      // state for every role so the next date (whether generated by this
      // batch or picked manually later) continues from where this left off.
      await Promise.all(entries.map((e) => saveLineUp(e)));
      await Promise.all(ALL_ROLES.map((role) => saveRotationQueue(role, finalQueues[role] ?? [])));

      return { generatedCount: entries.length, skippedDates };
    } catch (err) {
      console.error("Failed to auto-generate line-ups:", err);
      setError("Failed to auto-generate line-ups.");
      return null;
    } finally {
      setGenerating(false);
    }
  }

  return { generate, generating, error };
}